### ISSUE TITLE
Print list in reverse 

### ISSUE THREAD

**Issue by ChangedUser** [pedroallenrevez/jisho-api#1]
Hello, 
Absolutely love your implementation, but I was wondering if it would not be better to print the results in reverse or at least have a argument for it? 
Currently, if I use  ```jisho search word water``` it prints: 

```
水 (みず), 水 (み) [JLPT: jlpt-n5]
   2   │ 1. water (esp. cool, fresh water, e.g. drinking water)
   3   │ 2. fluid (esp. in an animal tissue), liquid
[...]
水滴 (すいてき) [JLPT: jlpt-n2]
1. drop of water
2. vessel for replenishing inkstone water
──────────────────────────────
浄水器 (じょうすいき)
1. water filter, water purification system
2. Water purification
```

The problem is, if the result has multiple objects, the most common case might not be present on screen and then I either have to scroll up or pipe the result into tac or bat, which both ruins the well done highlighting. 
I feel like having the most important result be print last is more intuitive.

**Comment by pedroallenrevez** [comment]
Hey! Thanks for the feedback, that is indeed a much more intuitive and a better design philosophy for CLIs.

**Comment by pedroallenrevez** [comment]
Version 0.1.3 reverses the search results, so the more common one comes at the end of the output!
