### ISSUE TITLE
Search tokenized words?

### ISSUE THREAD

**Issue by gbwalker** [pedroallenrevez/jisho-api#2]
Hi - this is a really great tool!

Currently, the regular Jisho search (`jisho.org/search/~`) tokenizes a long phrase into its component words. For example, it splits `昨日すき焼きを食べました` into `昨日/すき焼き/を/食べました`. (For some reason, #sentence returns no results here.)

Would you consider adding an implementation to iterate through these individual words (returning a `Word` search for each one)? Each one has a `data-word` tag on it, so they're easy to pull from the soup.

I'm happy to contribute something like this if you think it'd be useful and if you let me know where it would fit best.

**Comment by pedroallenrevez** [comment]
Hey, it seems like an interesting proposal! Just for thread reference here is an example: https://jisho.org/search/%E6%98%A8%E6%97%A5%E3%81%99%E3%81%8D%E7%84%BC%E3%81%8D%E3%82%92%E9%A3%9F%E3%81%B9%E3%81%BE%E3%81%97%E3%81%9F 

Unfortunately, the API makes use of three sources:
1. The word search feature provided by jisho.org themselves (this is what used for Words)
2. The kanji page, like [this](https://jisho.org/search/%E6%98%A8%20%23kanji) https://jisho.org/search/%E6%98%A8%20%23kanji (by using the #kanji search engine filter)
3. For [sentences](https://jisho.org/search/%E6%98%A8%20%23kanji), with #sentence filter

Maybe an additional request could be made for tokenizing. So, building a 
```
jisho search tokens 昨日すき焼きを食べました
```

**Comment by pedroallenrevez** [comment]
You can now do 
```
jisho search tokens 昨日すき焼きを食べました
``` 
OR
```
from jishi_api.tokenize import Tokens
r = Tokens.request('昨日すき焼きを食べました')
```

As for having a Word request per token, I personally think it's best to do so with the tools already available, like so:
```
from jisho_api.tokenize import Tokens
from jisho_api.word import Word

r = Tokens.request('昨日すき焼きを食べました')
for resp in r.data:
    wr = Word.request(resp.token)
```

**Comment by gbwalker** [comment]
I love it! It looks great. I agree that loop approach makes the most sense. Thanks so much!
