### ISSUE TITLE
PIP version not up to date

### ISSUE THREAD

**Issue by finia2NA** [pedroallenrevez/jisho-api#6]
The version of this libary that is hostet on PIP is still at the old commit f636e0e54231bcf0c596d3e03f81fb68e4c77b58 , meaning the tokenizer issues fixed by #5 are still there

It would be great if it were updated, as people pulling the library right now still don't have a working tokenizer (including me 😅)

**Comment by pedroallenrevez** [comment]
Sorry, I was under the impression that the version was already released.
I have released `0.1.5` that includes all the latest changes to the tokenizer,

Sorry for the delay,
Happy new year! 😁

**Comment by finia2NA** [comment]
Thank you!
