### ISSUE TITLE
It wasn't recognizing a utf-8 encoded txt, now it is, but I get nothing in the data folder

### ISSUE THREAD

**Issue by languagemaniac** [pedroallenrevez/jisho-api#8]
Hi, I would like to download definitions from Jisho.org for about 1000 kanji. If I understood correctly, this tool can do the job.

I've putted every Kanji in a new line, saved it on a utf-8 encoded txt file, and when I run "Jisho scrape kanji name.txt" I get these errors.

> C:\Jisho>jisho scrape kanji name.txt
> Traceback (most recent call last):
>   File "c:\users\username\appdata\local\programs\python\python38\lib\runpy.py", li
> ne 192, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\username\appdata\local\programs\python\python38\lib\runpy.py", li
> ne 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\username\AppData\Local\Programs\Python\Python38\Scripts\jisho.exe
> \__main__.py", line 7, in <module>
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \jisho_api\cli.py", line 209, in make_cli
>     main()
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \jisho_api\cli.py", line 102, in scrape_words
>     scraper(Word, _load_words(file_path), root_dump)
>   File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages
> \jisho_api\cli.py", line 89, in _load_words
>     txt = fp.read()
>   File "c:\users\username\appdata\local\programs\python\python38\lib\encodings\cp1
> 252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 39: chara
> cter maps to <undefined>

What can I do to solve this issue?

**Comment by languagemaniac** [comment]
I fixed the error substituting this line in cli.py (line 88)

> with open(file_path, "r") as fp:

with this other one

> with open(file_path, "r", encoding='utf-8') as fp:

however, now I check the data folder on ./jisho/data/kanji, and the folder is empty.

**Comment by languagemaniac** [comment]
I tried running jisho on the latest version of python installed on ubuntu, as I was running on 3.8 on windows 7 I thought that could be the problem. The only difference is I don't need to add "encoding='utf-8' to jisho cly.py for it to run, but still it's not scraping, or at least it's not creating any files inside the data/kanji folder

**Comment by pedroallenrevez** [comment]
Sorry for the delay in response, I will check up on this tonight and get back to you.

**Comment by MMatlacz** [comment]
Input words in https://github.com/pedroallenrevez/jisho-api/blob/9d52dcd8a3fab23d1fadd2c9305008705b3bdb7f/jisho_api/cli.py#L59 are overwritten in line 60.
If you remove lines 60, 81 and 84 then it works.

**Comment by languagemaniac** [comment]
> Input words in https://github.com/pedroallenrevez/jisho-api/blob/9d52dcd8a3fab23d1fadd2c9305008705b3bdb7f/jisho_api/cli.py#L59 are overwritten in line 60.
> If you remove lines 60, 81 and 84 then it works.

Will try, thanks!
